"""drop model id for chat and message

Revision ID: 53efd27aa40a
Revises: ae35c1701f10
Create Date: 2026-05-12 00:48:29.373440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53efd27aa40a'
down_revision: Union[str, Sequence[str], None] = 'ae35c1701f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'model_id')
    op.drop_column('chats', 'max_context_messages')
    op.drop_column('messages', 'model_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('model_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('chats', sa.Column('max_context_messages', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('chats', sa.Column('model_id', sa.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
