"""assistants tags and user id

Revision ID: ae35c1701f10
Revises: 16cb271c01ba
Create Date: 2026-05-11 22:57:33.615894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae35c1701f10'
down_revision: Union[str, Sequence[str], None] = '16cb271c01ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('tags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.alter_column('assistants', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assistants', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('assistants', 'tags')
    # ### end Alembic commands ###
